export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_NOW_PLAYING_REQUEST = 'FETCH_NOW_PLAYING_REQUEST';
export const FETCH_FAVORITES_REQUEST = 'FETCH_FAVORITES_REQUEST';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const FILL_FAVORITES = 'FILL_FAVORITES';